#!/usr/bin/env bash

build() {
	grep "^root" /etc/shadow | add_file - /etc/shadow 0600
	echo "root:x:0:0::/root:/bin/sh" | add_file - /etc/passwd 0644
}

help() {
cat <<- EOF
	Set the shell of root to /bin/sh and copy the password from the real /etc/shadow.
	Add after systemd hook, as it also writes the files. Additionally, you might need to change the password encryption scheme, if pam is not yet initialized in initrd.
EOF
}
